[package]
name = "advent_of_code_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
itertools = "0.10.5"
id_tree = "1.8"
pathfinding = "4.0"     # used in day 12
ndarray = "0.15.6"
